source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

#-------------------------------------------------------------------------------
# Core infrastructure
#-------------------------------------------------------------------------------

gem 'rails', '~> 7.1'

# the Ruby interface to the PostgreSQL RDBMS
gem 'pg'

# optimize and cache expensive computations
gem 'bootsnap'

# Puma is a simple, fast, multi-threaded, and highly parallel HTTP 1.1 server for Ruby/Rack applications.
gem 'puma'

# A fast JSON:API serializer for Ruby Objects.
gem 'jsonapi-serializer'

# Pagination library
gem 'will_paginate'

# Paginate in your headers, not in your response body. This follows the proposed RFC-8288 standard for Web linking.
gem 'api-pagination'

#-------------------------------------------------------------------------------
# Rails configuration, middleware, extensions
#-------------------------------------------------------------------------------

# XSS/CSRF safe JWT auth designed for SPA
gem 'jwt_sessions'

# An easy way to keep your users' passwords secure.
gem 'bcrypt'

# allows web applications to make cross domain AJAX calls without using workarounds such as JSONP
gem 'rack-cors'

# authorization system
gem 'pundit'

# Very simple Roles library without any authorization enforcement supporting scope on resource object.
gem 'rolify'

# Track changes to your models, for auditing or versioning.
gem 'paper_trail'

# application preloader
gem 'spring'

# listens to file modifications and notifies you about the changes.
gem 'listen'

# Exception tracking and logging from Ruby to Rollbar
gem 'rollbar'

#-------------------------------------------------------------------------------
# Assets
#-------------------------------------------------------------------------------
# Provides higher-level image processing helpers that are commonly needed when handling image uploads.
gem 'image_processing'

# A ruby wrapper for ImageMagick or GraphicsMagick command line.
gem 'mini_magick'

#-------------------------------------------------------------------------------
# 3rd-party & APIs
#-------------------------------------------------------------------------------
gem 'aws-sdk-s3', '~> 1.140'

#-------------------------------------------------------------------------------
# Services and utilities
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Development & Test
#-------------------------------------------------------------------------------

group :development, :test do
  # a testing framework
  gem 'rspec'
  gem 'rspec-rails'

  # Factories - libraries for setting up Ruby objects as test data
  gem 'factory_bot_rails'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  gem 'spring-watcher-listen'

  # preview emails
  gem "letter_opener", group: :development
end
