name: deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy SkladIS Backend to production
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $HOST
            User $USERNAME
            Port $PORT
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PORT: ${{ secrets.PORT }}
      - name: Run deploy script
        run: ssh deploy '/home/skladis/bin/deploy-skladis-backend'
