name: deploy
on:
  push:
    branches: [master]
    
jobs:
  deploy:
    name: deploy SkladIS Backend to production
    runs-on: ubuntu-latest
    steps:
    - name: executing deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: deploy-skladis-backend

